import Foundation

/// Real, spoken explanations for known UI elements, keyed by a lowercase
/// substring match against the element's title/description (AX titles stay
/// in the target app's own language regardless of AppSettings.shared.language -
/// only what we *say back* is translated). Falls back to a generic
/// "this is the {label}" phrasing for anything not in the pack.
///
/// `key` is a stable filename-safe identifier for each entry - Output uses
/// it to look up a pre-rendered Chatterbox audio clip
/// (Resources/audio/<language>/<key>.wav, generated by
/// chatterbox/generate_gaize_audio.py from this exact same list) before
/// falling back to the system voice. Keep `key` in sync with that script
/// when adding/editing entries.
///
/// Demo app is Messages — extend this table as new buttons come up in
/// rehearsal rather than hardcoding elsewhere.
enum KnowledgePack {
    struct Entry {
        let key: String
        let match: String
        let explanations: [AppLanguage: String]
    }

    static let entries: [Entry] = [
        Entry(key: "compose", match: "compose", explanations: [
            .english: "This starts a new conversation, so you can message someone new.",
            .spanish: "Esto inicia una nueva conversación para escribirle a alguien nuevo.",
            .french: "Ceci démarre une nouvelle conversation pour écrire à quelqu'un de nouveau.",
        ]),
        Entry(key: "compose", match: "new message", explanations: [
            .english: "This starts a new conversation, so you can message someone new.",
            .spanish: "Esto inicia una nueva conversación para escribirle a alguien nuevo.",
            .french: "Ceci démarre une nouvelle conversation pour écrire à quelqu'un de nouveau.",
        ]),
        // "send_later" must come before "send" - .first(where:) stops at
        // the first match, and "send later" contains "send" as a substring.
        Entry(key: "send_later", match: "send later", explanations: [
            .english: "This lets you schedule your message to send at a later time.",
            .spanish: "Esto te permite programar tu mensaje para enviarlo más tarde.",
            .french: "Ceci vous permet de programmer l'envoi de votre message plus tard.",
        ]),
        Entry(key: "send", match: "send", explanations: [
            .english: "This sends the message you've typed.",
            .spanish: "Esto envía el mensaje que escribiste.",
            .french: "Ceci envoie le message que vous avez écrit.",
        ]),
        Entry(key: "attach", match: "attach", explanations: [
            .english: "This lets you attach a photo, file, or other item to your message.",
            .spanish: "Esto te permite adjuntar una foto, archivo u otro elemento a tu mensaje.",
            .french: "Ceci vous permet de joindre une photo, un fichier ou un autre élément à votre message.",
        ]),
        Entry(key: "camera", match: "camera", explanations: [
            .english: "This lets you take a photo or video to send.",
            .spanish: "Esto te permite tomar una foto o video para enviar.",
            .french: "Ceci vous permet de prendre une photo ou une vidéo à envoyer.",
        ]),
        Entry(key: "details", match: "details", explanations: [
            .english: "This shows more information about the conversation, like who's in it.",
            .spanish: "Esto muestra más información sobre la conversación, como quién participa.",
            .french: "Ceci affiche plus d'informations sur la conversation, comme qui y participe.",
        ]),
        Entry(key: "audio_message", match: "audio message", explanations: [
            .english: "This lets you record and send a short voice message.",
            .spanish: "Esto te permite grabar y enviar un breve mensaje de voz.",
            .french: "Ceci vous permet d'enregistrer et d'envoyer un court message vocal.",
        ]),
        Entry(key: "app_store", match: "app store", explanations: [
            .english: "This opens extra features you can send in a message, like games or stickers.",
            .spanish: "Esto abre funciones adicionales que puedes enviar en un mensaje, como juegos o stickers.",
            .french: "Ceci ouvre des fonctionnalités supplémentaires à envoyer dans un message, comme des jeux ou des autocollants.",
        ]),
        Entry(key: "emoji", match: "emoji", explanations: [
            .english: "This opens emoji you can add to your message.",
            .spanish: "Esto abre emojis que puedes agregar a tu mensaje.",
            .french: "Ceci ouvre des emojis à ajouter à votre message.",
        ]),
        Entry(key: "search", match: "search", explanations: [
            .english: "This searches your conversations and messages.",
            .spanish: "Esto busca en tus conversaciones y mensajes.",
            .french: "Ceci recherche dans vos conversations et messages.",
        ]),
        // "back_to_goals" must come before "back" - .first(where:) stops
        // at the first match, and "back to goals" contains "back".
        Entry(key: "back_to_goals", match: "back to goals", explanations: [
            .english: "This takes you back to the list of goals.",
            .spanish: "Esto te lleva de vuelta a la lista de objetivos.",
            .french: "Ceci vous ramène à la liste des objectifs.",
        ]),
        Entry(key: "back", match: "back", explanations: [
            .english: "This takes you back to the previous screen.",
            .spanish: "Esto te lleva de vuelta a la pantalla anterior.",
            .french: "Ceci vous ramène à l'écran précédent.",
        ]),
        Entry(key: "facetime", match: "facetime", explanations: [
            .english: "This starts a FaceTime video call.",
            .spanish: "Esto inicia una videollamada de FaceTime.",
            .french: "Ceci démarre un appel vidéo FaceTime.",
        ]),
        Entry(key: "filter", match: "filter", explanations: [
            .english: "This filters and sorts your conversation list.",
            .spanish: "Esto filtra y ordena tu lista de conversaciones.",
            .french: "Ceci filtre et trie votre liste de conversations.",
        ]),
        Entry(key: "photos", match: "photos", explanations: [
            .english: "This lets you send a photo from your photo library.",
            .spanish: "Esto te permite enviar una foto de tu biblioteca de fotos.",
            .french: "Ceci vous permet d'envoyer une photo de votre photothèque.",
        ]),
        Entry(key: "stickers", match: "stickers", explanations: [
            .english: "This lets you send stickers in your message.",
            .spanish: "Esto te permite enviar stickers en tu mensaje.",
            .french: "Ceci vous permet d'envoyer des autocollants dans votre message.",
        ]),
        Entry(key: "polls", match: "polls", explanations: [
            .english: "This lets you create a poll for the group to vote on.",
            .spanish: "Esto te permite crear una encuesta para que el grupo vote.",
            .french: "Ceci vous permet de créer un sondage pour que le groupe vote.",
        ]),
        Entry(key: "genmoji", match: "genmoji", explanations: [
            .english: "This lets you create a custom emoji using a text description.",
            .spanish: "Esto te permite crear un emoji personalizado con una descripción de texto.",
            .french: "Ceci vous permet de créer un emoji personnalisé à partir d'une description texte.",
        ]),
        Entry(key: "image_playground", match: "image playground", explanations: [
            .english: "This lets you generate an image to send in your message.",
            .spanish: "Esto te permite generar una imagen para enviar en tu mensaje.",
            .french: "Ceci vous permet de générer une image à envoyer dans votre message.",
        ]),
        Entry(key: "hash_images", match: "#images", explanations: [
            .english: "This searches the web for images to send.",
            .spanish: "Esto busca imágenes en la web para enviar.",
            .french: "Ceci recherche des images sur le web à envoyer.",
        ]),
        Entry(key: "message_effects", match: "message effects", explanations: [
            .english: "This adds a fun visual effect to your message, like balloons or confetti.",
            .spanish: "Esto agrega un efecto visual divertido a tu mensaje, como globos o confeti.",
            .french: "Ceci ajoute un effet visuel amusant à votre message, comme des ballons ou des confettis.",
        ]),
        Entry(key: "to_field", match: "to:", explanations: [
            .english: "This is where you type or say who you're sending the message to.",
            .spanish: "Aquí escribes o dices a quién le estás enviando el mensaje.",
            .french: "C'est ici que vous tapez ou dites à qui vous envoyez le message.",
        ]),
        // "message_field" must come after "message effects" and "new
        // message" - .first(where:) stops at the first match, and both of
        // those titles contain the plain word "message".
        Entry(key: "message_field", match: "message", explanations: [
            .english: "This is where you type your message before sending it.",
            .spanish: "Aquí escribes tu mensaje antes de enviarlo.",
            .french: "C'est ici que vous écrivez votre message avant de l'envoyer.",
        ]),

        // Gaize's own website buttons, not Messages.
        Entry(key: "home", match: "back to home", explanations: [
            .english: "This takes you back to the home screen.",
            .spanish: "Esto te lleva de vuelta a la pantalla de inicio.",
            .french: "Ceci vous ramène à l'écran d'accueil.",
        ]),
        Entry(key: "learn_this_goal", match: "learn this goal", explanations: [
            .english: "This starts the guided walkthrough for this goal, step by step.",
            .spanish: "Esto inicia el recorrido guiado para este objetivo, paso a paso.",
            .french: "Ceci démarre le guide pas à pas pour cet objectif.",
        ]),
        Entry(key: "take_a_quiz", match: "take a quiz", explanations: [
            .english: "This gives you a short quiz to check what you learned.",
            .spanish: "Esto te da un breve cuestionario para comprobar lo que aprendiste.",
            .french: "Ceci vous propose un court quiz pour vérifier ce que vous avez appris.",
        ]),
        Entry(key: "try_a_scenario", match: "try a scenario", explanations: [
            .english: "This gives you a real task to complete, and checks that you did it correctly.",
            .spanish: "Esto te da una tarea real para completar, y verifica que la hiciste correctamente.",
            .french: "Ceci vous donne une tâche réelle à accomplir, et vérifie que vous l'avez bien faite.",
        ]),
    ]

    /// The matched entry for an element, if any - carries both the key
    /// (for audio lookup) and the translated text (for TTS fallback).
    static func matchedEntry(for element: SensedElement) -> Entry? {
        let label = element.title.isEmpty ? element.role : element.title
        let haystack = label.lowercased()
        return entries.first(where: { haystack.contains($0.match) })
    }

    static func explanation(for element: SensedElement) -> String {
        let label = element.title.isEmpty ? element.role : element.title
        let language = AppSettings.shared.language

        if let match = matchedEntry(for: element), let text = match.explanations[language] {
            return text
        }

        return language.genericExplanationTemplate(label)
    }

    static func confirmation(for element: SensedElement) -> String {
        let label = element.title.isEmpty ? element.role : element.title
        return AppSettings.shared.language.confirmationTemplate(label)
    }
}
